repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.14.2
  hooks:
    # Run the linter.
    - id: ruff-check
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format

# # Run ty type checker
# - repo: local
#   hooks:
#     - id: ty
#       name: ty
#       entry: uv run ty check
#       language: system
#       types: [python]
#       pass_filenames: false
#       always_run: true
