name: cfclient
adopt-info: cfclient
license: GPL-3.0
summary: Crazyflie client
description: |
  Crazyflie client
base: core18
confinement: strict
icon: snap/gui/cfclient.png

# Until we can use pyqt5 from apt, we are stuck to amd64 only
architectures:
  - build-on: amd64


parts:
  cfclient:
    plugin: python
    python-version: python3
    source-type: git
    override-pull: | # This override tells snapcraft to use latest release tag
      snapcraftctl pull
      last_tag="$(git describe --tags --abbrev=0 --match '[0-9]*.*')"
      git fetch
      git checkout "${last_tag}"
      snapcraftctl set-version "${last_tag}"
    source: https://github.com/bitcraze/crazyflie-clients-python.git
    stage-packages:
      - libglu1-mesa
      - libxcb-glx0

apps:
  cfclient:
    command: python3 -m cfclient.gui
    extensions:
      - kde-neon
    plugs:
      - home
      - opengl
      - network
      - network-bind
      - raw-usb
      - joystick
