# This is a basic workflow to help you get started with Actions

name: CI experiment

# Controls when the action will run.
on:
  workflow_dispatch:

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          python_version: ["3.8","3.9", "3.10", "3.11","3.12"]
        fail-fast: false
    env:
      TEST_FILE: client-sanity-${{github.run_number}}-${{ matrix.python_version }}
      timeout-minutes: 120
      container:
        image: python:${{ matrix.python_version }}-bullseye
        options: --privileged
        steps:
    - name: Upgrade pip
      run:  |
        pip3 install --upgrade pip

    - name: install dependencies
      run: |
        pip3 install pytest
        pip3 install pytest-qt

    - name: Check out sources
      uses: actions/checkout@v4
    
    - name: Install client
      run: |
        pip3 install -e .

     - name: Run test suite
      run: pytest --verbose --html=${{env.TEST_FILE}}.html --junit-xml ${{env.TEST_FILE}}.xml
      
    - name: Upload test file
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ${{env.TEST_FILE}}_results
        if-no-files-found: warn
        path: |
          ${{env.TEST_FILE}}.html
          ${{env.TEST_FILE}}.xml
          assets/style.css

    - name: Pretty print test results
      if: always()
      uses: pmeier/pytest-results-action@main
      with:
        path: ${{env.TEST_FILE}}.xml
        summary: true
        title: Test results